env: develop
grpc:
  host: ${GRPC_HOST}
  port: ${GRPC_PORT}
db:
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
kafka:
  host: ${KAFKA_HOST}
  port: ${KAFKA_PORT
logger:
  service: orchestrator-service
  output-type: console
  level: debug
