// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: orchestrator-service/v1/orchestrator-service.proto

package orchestratorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Orchestrator_CreateBot_FullMethodName     = "/orchestratorv1.Orchestrator/CreateBot"
	Orchestrator_GetBot_FullMethodName        = "/orchestratorv1.Orchestrator/GetBot"
	Orchestrator_GetAllBots_FullMethodName    = "/orchestratorv1.Orchestrator/GetAllBots"
	Orchestrator_StopBot_FullMethodName       = "/orchestratorv1.Orchestrator/StopBot"
	Orchestrator_StopBots_FullMethodName      = "/orchestratorv1.Orchestrator/StopBots"
	Orchestrator_StartBot_FullMethodName      = "/orchestratorv1.Orchestrator/StartBot"
	Orchestrator_StartBots_FullMethodName     = "/orchestratorv1.Orchestrator/StartBots"
	Orchestrator_RestartBot_FullMethodName    = "/orchestratorv1.Orchestrator/RestartBot"
	Orchestrator_DeleteBot_FullMethodName     = "/orchestratorv1.Orchestrator/DeleteBot"
	Orchestrator_DeleteBots_FullMethodName    = "/orchestratorv1.Orchestrator/DeleteBots"
	Orchestrator_DeleteAllBots_FullMethodName = "/orchestratorv1.Orchestrator/DeleteAllBots"
)

// OrchestratorClient is the client API for Orchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorClient interface {
	// METADATA: jwt token of user
	CreateBot(ctx context.Context, in *CreateBotReq, opts ...grpc.CallOption) (*Bot, error)
	// METADATA: jwt token of user
	GetBot(ctx context.Context, in *GetBotReq, opts ...grpc.CallOption) (*Bot, error)
	// METADATA: jwt token of user
	GetAllBots(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllBotsResp, error)
	// METADATA: jwt token of user
	StopBot(ctx context.Context, in *StopBotReq, opts ...grpc.CallOption) (*Bot, error)
	// METADATA: jwt token of user
	StopBots(ctx context.Context, in *StopBotsReq, opts ...grpc.CallOption) (*StopBotsResp, error)
	// METADATA: jwt token of user
	StartBot(ctx context.Context, in *StartBotReq, opts ...grpc.CallOption) (*Bot, error)
	// METADATA: jwt token of user
	StartBots(ctx context.Context, in *StartBotsReq, opts ...grpc.CallOption) (*StartBotsResp, error)
	// METADATA: jwt token of user
	RestartBot(ctx context.Context, in *RestartBotReq, opts ...grpc.CallOption) (*Bot, error)
	// METADATA: jwt token of user
	DeleteBot(ctx context.Context, in *DeleteBotReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// METADATA: jwt token of user
	DeleteBots(ctx context.Context, in *DeleteBotsReq, opts ...grpc.CallOption) (*DeleteBotsResp, error)
	// METADATA: jwt token of user
	DeleteAllBots(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DeleteAllBotsResp, error)
}

type orchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorClient(cc grpc.ClientConnInterface) OrchestratorClient {
	return &orchestratorClient{cc}
}

func (c *orchestratorClient) CreateBot(ctx context.Context, in *CreateBotReq, opts ...grpc.CallOption) (*Bot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bot)
	err := c.cc.Invoke(ctx, Orchestrator_CreateBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) GetBot(ctx context.Context, in *GetBotReq, opts ...grpc.CallOption) (*Bot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bot)
	err := c.cc.Invoke(ctx, Orchestrator_GetBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) GetAllBots(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllBotsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllBotsResp)
	err := c.cc.Invoke(ctx, Orchestrator_GetAllBots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) StopBot(ctx context.Context, in *StopBotReq, opts ...grpc.CallOption) (*Bot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bot)
	err := c.cc.Invoke(ctx, Orchestrator_StopBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) StopBots(ctx context.Context, in *StopBotsReq, opts ...grpc.CallOption) (*StopBotsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopBotsResp)
	err := c.cc.Invoke(ctx, Orchestrator_StopBots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) StartBot(ctx context.Context, in *StartBotReq, opts ...grpc.CallOption) (*Bot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bot)
	err := c.cc.Invoke(ctx, Orchestrator_StartBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) StartBots(ctx context.Context, in *StartBotsReq, opts ...grpc.CallOption) (*StartBotsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartBotsResp)
	err := c.cc.Invoke(ctx, Orchestrator_StartBots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) RestartBot(ctx context.Context, in *RestartBotReq, opts ...grpc.CallOption) (*Bot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bot)
	err := c.cc.Invoke(ctx, Orchestrator_RestartBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) DeleteBot(ctx context.Context, in *DeleteBotReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Orchestrator_DeleteBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) DeleteBots(ctx context.Context, in *DeleteBotsReq, opts ...grpc.CallOption) (*DeleteBotsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBotsResp)
	err := c.cc.Invoke(ctx, Orchestrator_DeleteBots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) DeleteAllBots(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DeleteAllBotsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAllBotsResp)
	err := c.cc.Invoke(ctx, Orchestrator_DeleteAllBots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServer is the server API for Orchestrator service.
// All implementations must embed UnimplementedOrchestratorServer
// for forward compatibility.
type OrchestratorServer interface {
	// METADATA: jwt token of user
	CreateBot(context.Context, *CreateBotReq) (*Bot, error)
	// METADATA: jwt token of user
	GetBot(context.Context, *GetBotReq) (*Bot, error)
	// METADATA: jwt token of user
	GetAllBots(context.Context, *emptypb.Empty) (*GetAllBotsResp, error)
	// METADATA: jwt token of user
	StopBot(context.Context, *StopBotReq) (*Bot, error)
	// METADATA: jwt token of user
	StopBots(context.Context, *StopBotsReq) (*StopBotsResp, error)
	// METADATA: jwt token of user
	StartBot(context.Context, *StartBotReq) (*Bot, error)
	// METADATA: jwt token of user
	StartBots(context.Context, *StartBotsReq) (*StartBotsResp, error)
	// METADATA: jwt token of user
	RestartBot(context.Context, *RestartBotReq) (*Bot, error)
	// METADATA: jwt token of user
	DeleteBot(context.Context, *DeleteBotReq) (*emptypb.Empty, error)
	// METADATA: jwt token of user
	DeleteBots(context.Context, *DeleteBotsReq) (*DeleteBotsResp, error)
	// METADATA: jwt token of user
	DeleteAllBots(context.Context, *emptypb.Empty) (*DeleteAllBotsResp, error)
	mustEmbedUnimplementedOrchestratorServer()
}

// UnimplementedOrchestratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorServer struct{}

func (UnimplementedOrchestratorServer) CreateBot(context.Context, *CreateBotReq) (*Bot, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBot not implemented")
}
func (UnimplementedOrchestratorServer) GetBot(context.Context, *GetBotReq) (*Bot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBot not implemented")
}
func (UnimplementedOrchestratorServer) GetAllBots(context.Context, *emptypb.Empty) (*GetAllBotsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllBots not implemented")
}
func (UnimplementedOrchestratorServer) StopBot(context.Context, *StopBotReq) (*Bot, error) {
	return nil, status.Error(codes.Unimplemented, "method StopBot not implemented")
}
func (UnimplementedOrchestratorServer) StopBots(context.Context, *StopBotsReq) (*StopBotsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method StopBots not implemented")
}
func (UnimplementedOrchestratorServer) StartBot(context.Context, *StartBotReq) (*Bot, error) {
	return nil, status.Error(codes.Unimplemented, "method StartBot not implemented")
}
func (UnimplementedOrchestratorServer) StartBots(context.Context, *StartBotsReq) (*StartBotsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method StartBots not implemented")
}
func (UnimplementedOrchestratorServer) RestartBot(context.Context, *RestartBotReq) (*Bot, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartBot not implemented")
}
func (UnimplementedOrchestratorServer) DeleteBot(context.Context, *DeleteBotReq) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBot not implemented")
}
func (UnimplementedOrchestratorServer) DeleteBots(context.Context, *DeleteBotsReq) (*DeleteBotsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBots not implemented")
}
func (UnimplementedOrchestratorServer) DeleteAllBots(context.Context, *emptypb.Empty) (*DeleteAllBotsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAllBots not implemented")
}
func (UnimplementedOrchestratorServer) mustEmbedUnimplementedOrchestratorServer() {}
func (UnimplementedOrchestratorServer) testEmbeddedByValue()                      {}

// UnsafeOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServer will
// result in compilation errors.
type UnsafeOrchestratorServer interface {
	mustEmbedUnimplementedOrchestratorServer()
}

func RegisterOrchestratorServer(s grpc.ServiceRegistrar, srv OrchestratorServer) {
	// If the following call panics, it indicates UnimplementedOrchestratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Orchestrator_ServiceDesc, srv)
}

func _Orchestrator_CreateBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).CreateBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_CreateBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).CreateBot(ctx, req.(*CreateBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_GetBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).GetBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_GetBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).GetBot(ctx, req.(*GetBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_GetAllBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).GetAllBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_GetAllBots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).GetAllBots(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_StopBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).StopBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_StopBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).StopBot(ctx, req.(*StopBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_StopBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopBotsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).StopBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_StopBots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).StopBots(ctx, req.(*StopBotsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_StartBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).StartBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_StartBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).StartBot(ctx, req.(*StartBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_StartBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartBotsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).StartBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_StartBots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).StartBots(ctx, req.(*StartBotsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_RestartBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).RestartBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_RestartBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).RestartBot(ctx, req.(*RestartBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_DeleteBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).DeleteBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_DeleteBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).DeleteBot(ctx, req.(*DeleteBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_DeleteBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBotsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).DeleteBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_DeleteBots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).DeleteBots(ctx, req.(*DeleteBotsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_DeleteAllBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).DeleteAllBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_DeleteAllBots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).DeleteAllBots(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Orchestrator_ServiceDesc is the grpc.ServiceDesc for Orchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Orchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestratorv1.Orchestrator",
	HandlerType: (*OrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBot",
			Handler:    _Orchestrator_CreateBot_Handler,
		},
		{
			MethodName: "GetBot",
			Handler:    _Orchestrator_GetBot_Handler,
		},
		{
			MethodName: "GetAllBots",
			Handler:    _Orchestrator_GetAllBots_Handler,
		},
		{
			MethodName: "StopBot",
			Handler:    _Orchestrator_StopBot_Handler,
		},
		{
			MethodName: "StopBots",
			Handler:    _Orchestrator_StopBots_Handler,
		},
		{
			MethodName: "StartBot",
			Handler:    _Orchestrator_StartBot_Handler,
		},
		{
			MethodName: "StartBots",
			Handler:    _Orchestrator_StartBots_Handler,
		},
		{
			MethodName: "RestartBot",
			Handler:    _Orchestrator_RestartBot_Handler,
		},
		{
			MethodName: "DeleteBot",
			Handler:    _Orchestrator_DeleteBot_Handler,
		},
		{
			MethodName: "DeleteBots",
			Handler:    _Orchestrator_DeleteBots_Handler,
		},
		{
			MethodName: "DeleteAllBots",
			Handler:    _Orchestrator_DeleteAllBots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orchestrator-service/v1/orchestrator-service.proto",
}
