// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: orchestrator-service/v1/orchestrator-service.proto

package orchestratorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BotStatus int32

const (
	BotStatus_BOT_STATUS_UNKNOWN    BotStatus = 0
	BotStatus_BOT_STATUS_CREATING   BotStatus = 1
	BotStatus_BOT_STATUS_STARTING   BotStatus = 2
	BotStatus_BOT_STATUS_RUNNING    BotStatus = 3
	BotStatus_BOT_STATUS_STOPPING   BotStatus = 4
	BotStatus_BOT_STATUS_STOPPED    BotStatus = 5
	BotStatus_BOT_STATUS_RESTARTING BotStatus = 6
	BotStatus_BOT_STATUS_DELETING   BotStatus = 7
	BotStatus_BOT_STATUS_ERROR      BotStatus = 8
)

// Enum value maps for BotStatus.
var (
	BotStatus_name = map[int32]string{
		0: "BOT_STATUS_UNKNOWN",
		1: "BOT_STATUS_CREATING",
		2: "BOT_STATUS_STARTING",
		3: "BOT_STATUS_RUNNING",
		4: "BOT_STATUS_STOPPING",
		5: "BOT_STATUS_STOPPED",
		6: "BOT_STATUS_RESTARTING",
		7: "BOT_STATUS_DELETING",
		8: "BOT_STATUS_ERROR",
	}
	BotStatus_value = map[string]int32{
		"BOT_STATUS_UNKNOWN":    0,
		"BOT_STATUS_CREATING":   1,
		"BOT_STATUS_STARTING":   2,
		"BOT_STATUS_RUNNING":    3,
		"BOT_STATUS_STOPPING":   4,
		"BOT_STATUS_STOPPED":    5,
		"BOT_STATUS_RESTARTING": 6,
		"BOT_STATUS_DELETING":   7,
		"BOT_STATUS_ERROR":      8,
	}
)

func (x BotStatus) Enum() *BotStatus {
	p := new(BotStatus)
	*p = x
	return p
}

func (x BotStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BotStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_orchestrator_service_v1_orchestrator_service_proto_enumTypes[0].Descriptor()
}

func (BotStatus) Type() protoreflect.EnumType {
	return &file_orchestrator_service_v1_orchestrator_service_proto_enumTypes[0]
}

func (x BotStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BotStatus.Descriptor instead.
func (BotStatus) EnumDescriptor() ([]byte, []int) {
	return file_orchestrator_service_v1_orchestrator_service_proto_rawDescGZIP(), []int{0}
}

type Bot struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status BotStatus              `protobuf:"varint,3,opt,name=status,proto3,enum=orchestratorv1.BotStatus" json:"status,omitempty"`
	Name   string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// filled when status = error
	LastError     string                 `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bot) Reset() {
	*x = Bot{}
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bot) ProtoMessage() {}

func (x *Bot) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bot.ProtoReflect.Descriptor instead.
func (*Bot) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_v1_orchestrator_service_proto_rawDescGZIP(), []int{0}
}

func (x *Bot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bot) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Bot) GetStatus() BotStatus {
	if x != nil {
		return x.Status
	}
	return BotStatus_BOT_STATUS_UNKNOWN
}

func (x *Bot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bot) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Bot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Bot) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateBotReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBotReq) Reset() {
	*x = CreateBotReq{}
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBotReq) ProtoMessage() {}

func (x *CreateBotReq) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBotReq.ProtoReflect.Descriptor instead.
func (*CreateBotReq) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_v1_orchestrator_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBotReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBotReq) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type GetBotReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBotReq) Reset() {
	*x = GetBotReq{}
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotReq) ProtoMessage() {}

func (x *GetBotReq) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotReq.ProtoReflect.Descriptor instead.
func (*GetBotReq) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_v1_orchestrator_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetBotReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAllBotsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bots          []*Bot                 `protobuf:"bytes,1,rep,name=bots,proto3" json:"bots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBotsResp) Reset() {
	*x = GetAllBotsResp{}
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBotsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBotsResp) ProtoMessage() {}

func (x *GetAllBotsResp) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBotsResp.ProtoReflect.Descriptor instead.
func (*GetAllBotsResp) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_v1_orchestrator_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllBotsResp) GetBots() []*Bot {
	if x != nil {
		return x.Bots
	}
	return nil
}

type StopBotReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopBotReq) Reset() {
	*x = StopBotReq{}
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopBotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopBotReq) ProtoMessage() {}

func (x *StopBotReq) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopBotReq.ProtoReflect.Descriptor instead.
func (*StopBotReq) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_v1_orchestrator_service_proto_rawDescGZIP(), []int{4}
}

func (x *StopBotReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopBotsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopBotsReq) Reset() {
	*x = StopBotsReq{}
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopBotsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopBotsReq) ProtoMessage() {}

func (x *StopBotsReq) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopBotsReq.ProtoReflect.Descriptor instead.
func (*StopBotsReq) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_v1_orchestrator_service_proto_rawDescGZIP(), []int{5}
}

func (x *StopBotsReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type StopBotsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bots          []*Bot                 `protobuf:"bytes,1,rep,name=bots,proto3" json:"bots,omitempty"`
	AllSucceeded  bool                   `protobuf:"varint,2,opt,name=all_succeeded,json=allSucceeded,proto3" json:"all_succeeded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopBotsResp) Reset() {
	*x = StopBotsResp{}
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopBotsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopBotsResp) ProtoMessage() {}

func (x *StopBotsResp) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopBotsResp.ProtoReflect.Descriptor instead.
func (*StopBotsResp) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_v1_orchestrator_service_proto_rawDescGZIP(), []int{6}
}

func (x *StopBotsResp) GetBots() []*Bot {
	if x != nil {
		return x.Bots
	}
	return nil
}

func (x *StopBotsResp) GetAllSucceeded() bool {
	if x != nil {
		return x.AllSucceeded
	}
	return false
}

type StartBotReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartBotReq) Reset() {
	*x = StartBotReq{}
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBotReq) ProtoMessage() {}

func (x *StartBotReq) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBotReq.ProtoReflect.Descriptor instead.
func (*StartBotReq) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_v1_orchestrator_service_proto_rawDescGZIP(), []int{7}
}

func (x *StartBotReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StartBotsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartBotsReq) Reset() {
	*x = StartBotsReq{}
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBotsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBotsReq) ProtoMessage() {}

func (x *StartBotsReq) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBotsReq.ProtoReflect.Descriptor instead.
func (*StartBotsReq) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_v1_orchestrator_service_proto_rawDescGZIP(), []int{8}
}

func (x *StartBotsReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type StartBotsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bots          []*Bot                 `protobuf:"bytes,1,rep,name=bots,proto3" json:"bots,omitempty"`
	AllSucceeded  bool                   `protobuf:"varint,2,opt,name=all_succeeded,json=allSucceeded,proto3" json:"all_succeeded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartBotsResp) Reset() {
	*x = StartBotsResp{}
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBotsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBotsResp) ProtoMessage() {}

func (x *StartBotsResp) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBotsResp.ProtoReflect.Descriptor instead.
func (*StartBotsResp) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_v1_orchestrator_service_proto_rawDescGZIP(), []int{9}
}

func (x *StartBotsResp) GetBots() []*Bot {
	if x != nil {
		return x.Bots
	}
	return nil
}

func (x *StartBotsResp) GetAllSucceeded() bool {
	if x != nil {
		return x.AllSucceeded
	}
	return false
}

type RestartBotReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartBotReq) Reset() {
	*x = RestartBotReq{}
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartBotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartBotReq) ProtoMessage() {}

func (x *RestartBotReq) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartBotReq.ProtoReflect.Descriptor instead.
func (*RestartBotReq) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_v1_orchestrator_service_proto_rawDescGZIP(), []int{10}
}

func (x *RestartBotReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBotReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBotReq) Reset() {
	*x = DeleteBotReq{}
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBotReq) ProtoMessage() {}

func (x *DeleteBotReq) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBotReq.ProtoReflect.Descriptor instead.
func (*DeleteBotReq) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_v1_orchestrator_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteBotReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBotsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBotsReq) Reset() {
	*x = DeleteBotsReq{}
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBotsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBotsReq) ProtoMessage() {}

func (x *DeleteBotsReq) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBotsReq.ProtoReflect.Descriptor instead.
func (*DeleteBotsReq) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_v1_orchestrator_service_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteBotsReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteBotsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllSucceeded  bool                   `protobuf:"varint,1,opt,name=all_succeeded,json=allSucceeded,proto3" json:"all_succeeded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBotsResp) Reset() {
	*x = DeleteBotsResp{}
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBotsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBotsResp) ProtoMessage() {}

func (x *DeleteBotsResp) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBotsResp.ProtoReflect.Descriptor instead.
func (*DeleteBotsResp) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_v1_orchestrator_service_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteBotsResp) GetAllSucceeded() bool {
	if x != nil {
		return x.AllSucceeded
	}
	return false
}

type DeleteAllBotsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllSucceeded  bool                   `protobuf:"varint,1,opt,name=all_succeeded,json=allSucceeded,proto3" json:"all_succeeded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAllBotsResp) Reset() {
	*x = DeleteAllBotsResp{}
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAllBotsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAllBotsResp) ProtoMessage() {}

func (x *DeleteAllBotsResp) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_service_v1_orchestrator_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAllBotsResp.ProtoReflect.Descriptor instead.
func (*DeleteAllBotsResp) Descriptor() ([]byte, []int) {
	return file_orchestrator_service_v1_orchestrator_service_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteAllBotsResp) GetAllSucceeded() bool {
	if x != nil {
		return x.AllSucceeded
	}
	return false
}

var File_orchestrator_service_v1_orchestrator_service_proto protoreflect.FileDescriptor

const file_orchestrator_service_v1_orchestrator_service_proto_rawDesc = "" +
	"\n" +
	"2orchestrator-service/v1/orchestrator-service.proto\x12\x0eorchestratorv1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x02\n" +
	"\x03Bot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.orchestratorv1.BotStatusR\x06status\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastError\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\";\n" +
	"\fCreateBotReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"\x1b\n" +
	"\tGetBotReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x0eGetAllBotsResp\x12'\n" +
	"\x04bots\x18\x01 \x03(\v2\x13.orchestratorv1.BotR\x04bots\"\x1c\n" +
	"\n" +
	"StopBotReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\vStopBotsReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\\\n" +
	"\fStopBotsResp\x12'\n" +
	"\x04bots\x18\x01 \x03(\v2\x13.orchestratorv1.BotR\x04bots\x12#\n" +
	"\rall_succeeded\x18\x02 \x01(\bR\fallSucceeded\"\x1d\n" +
	"\vStartBotReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\" \n" +
	"\fStartBotsReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"]\n" +
	"\rStartBotsResp\x12'\n" +
	"\x04bots\x18\x01 \x03(\v2\x13.orchestratorv1.BotR\x04bots\x12#\n" +
	"\rall_succeeded\x18\x02 \x01(\bR\fallSucceeded\"\x1f\n" +
	"\rRestartBotReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1e\n" +
	"\fDeleteBotReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\rDeleteBotsReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"5\n" +
	"\x0eDeleteBotsResp\x12#\n" +
	"\rall_succeeded\x18\x01 \x01(\bR\fallSucceeded\"8\n" +
	"\x11DeleteAllBotsResp\x12#\n" +
	"\rall_succeeded\x18\x01 \x01(\bR\fallSucceeded*\xe8\x01\n" +
	"\tBotStatus\x12\x16\n" +
	"\x12BOT_STATUS_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13BOT_STATUS_CREATING\x10\x01\x12\x17\n" +
	"\x13BOT_STATUS_STARTING\x10\x02\x12\x16\n" +
	"\x12BOT_STATUS_RUNNING\x10\x03\x12\x17\n" +
	"\x13BOT_STATUS_STOPPING\x10\x04\x12\x16\n" +
	"\x12BOT_STATUS_STOPPED\x10\x05\x12\x19\n" +
	"\x15BOT_STATUS_RESTARTING\x10\x06\x12\x17\n" +
	"\x13BOT_STATUS_DELETING\x10\a\x12\x14\n" +
	"\x10BOT_STATUS_ERROR\x10\b2\xf7\x05\n" +
	"\fOrchestrator\x12>\n" +
	"\tCreateBot\x12\x1c.orchestratorv1.CreateBotReq\x1a\x13.orchestratorv1.Bot\x128\n" +
	"\x06GetBot\x12\x19.orchestratorv1.GetBotReq\x1a\x13.orchestratorv1.Bot\x12D\n" +
	"\n" +
	"GetAllBots\x12\x16.google.protobuf.Empty\x1a\x1e.orchestratorv1.GetAllBotsResp\x12:\n" +
	"\aStopBot\x12\x1a.orchestratorv1.StopBotReq\x1a\x13.orchestratorv1.Bot\x12E\n" +
	"\bStopBots\x12\x1b.orchestratorv1.StopBotsReq\x1a\x1c.orchestratorv1.StopBotsResp\x12<\n" +
	"\bStartBot\x12\x1b.orchestratorv1.StartBotReq\x1a\x13.orchestratorv1.Bot\x12H\n" +
	"\tStartBots\x12\x1c.orchestratorv1.StartBotsReq\x1a\x1d.orchestratorv1.StartBotsResp\x12@\n" +
	"\n" +
	"RestartBot\x12\x1d.orchestratorv1.RestartBotReq\x1a\x13.orchestratorv1.Bot\x12A\n" +
	"\tDeleteBot\x12\x1c.orchestratorv1.DeleteBotReq\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\n" +
	"DeleteBots\x12\x1d.orchestratorv1.DeleteBotsReq\x1a\x1e.orchestratorv1.DeleteBotsResp\x12J\n" +
	"\rDeleteAllBots\x12\x16.google.protobuf.Empty\x1a!.orchestratorv1.DeleteAllBotsRespBKZIgithub.com/braunkc/ai-bot-constructor/orchestrator-service;orchestratorpbb\x06proto3"

var (
	file_orchestrator_service_v1_orchestrator_service_proto_rawDescOnce sync.Once
	file_orchestrator_service_v1_orchestrator_service_proto_rawDescData []byte
)

func file_orchestrator_service_v1_orchestrator_service_proto_rawDescGZIP() []byte {
	file_orchestrator_service_v1_orchestrator_service_proto_rawDescOnce.Do(func() {
		file_orchestrator_service_v1_orchestrator_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_service_v1_orchestrator_service_proto_rawDesc), len(file_orchestrator_service_v1_orchestrator_service_proto_rawDesc)))
	})
	return file_orchestrator_service_v1_orchestrator_service_proto_rawDescData
}

var file_orchestrator_service_v1_orchestrator_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_orchestrator_service_v1_orchestrator_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_orchestrator_service_v1_orchestrator_service_proto_goTypes = []any{
	(BotStatus)(0),                // 0: orchestratorv1.BotStatus
	(*Bot)(nil),                   // 1: orchestratorv1.Bot
	(*CreateBotReq)(nil),          // 2: orchestratorv1.CreateBotReq
	(*GetBotReq)(nil),             // 3: orchestratorv1.GetBotReq
	(*GetAllBotsResp)(nil),        // 4: orchestratorv1.GetAllBotsResp
	(*StopBotReq)(nil),            // 5: orchestratorv1.StopBotReq
	(*StopBotsReq)(nil),           // 6: orchestratorv1.StopBotsReq
	(*StopBotsResp)(nil),          // 7: orchestratorv1.StopBotsResp
	(*StartBotReq)(nil),           // 8: orchestratorv1.StartBotReq
	(*StartBotsReq)(nil),          // 9: orchestratorv1.StartBotsReq
	(*StartBotsResp)(nil),         // 10: orchestratorv1.StartBotsResp
	(*RestartBotReq)(nil),         // 11: orchestratorv1.RestartBotReq
	(*DeleteBotReq)(nil),          // 12: orchestratorv1.DeleteBotReq
	(*DeleteBotsReq)(nil),         // 13: orchestratorv1.DeleteBotsReq
	(*DeleteBotsResp)(nil),        // 14: orchestratorv1.DeleteBotsResp
	(*DeleteAllBotsResp)(nil),     // 15: orchestratorv1.DeleteAllBotsResp
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 17: google.protobuf.Empty
}
var file_orchestrator_service_v1_orchestrator_service_proto_depIdxs = []int32{
	0,  // 0: orchestratorv1.Bot.status:type_name -> orchestratorv1.BotStatus
	16, // 1: orchestratorv1.Bot.created_at:type_name -> google.protobuf.Timestamp
	16, // 2: orchestratorv1.Bot.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: orchestratorv1.GetAllBotsResp.bots:type_name -> orchestratorv1.Bot
	1,  // 4: orchestratorv1.StopBotsResp.bots:type_name -> orchestratorv1.Bot
	1,  // 5: orchestratorv1.StartBotsResp.bots:type_name -> orchestratorv1.Bot
	2,  // 6: orchestratorv1.Orchestrator.CreateBot:input_type -> orchestratorv1.CreateBotReq
	3,  // 7: orchestratorv1.Orchestrator.GetBot:input_type -> orchestratorv1.GetBotReq
	17, // 8: orchestratorv1.Orchestrator.GetAllBots:input_type -> google.protobuf.Empty
	5,  // 9: orchestratorv1.Orchestrator.StopBot:input_type -> orchestratorv1.StopBotReq
	6,  // 10: orchestratorv1.Orchestrator.StopBots:input_type -> orchestratorv1.StopBotsReq
	8,  // 11: orchestratorv1.Orchestrator.StartBot:input_type -> orchestratorv1.StartBotReq
	9,  // 12: orchestratorv1.Orchestrator.StartBots:input_type -> orchestratorv1.StartBotsReq
	11, // 13: orchestratorv1.Orchestrator.RestartBot:input_type -> orchestratorv1.RestartBotReq
	12, // 14: orchestratorv1.Orchestrator.DeleteBot:input_type -> orchestratorv1.DeleteBotReq
	13, // 15: orchestratorv1.Orchestrator.DeleteBots:input_type -> orchestratorv1.DeleteBotsReq
	17, // 16: orchestratorv1.Orchestrator.DeleteAllBots:input_type -> google.protobuf.Empty
	1,  // 17: orchestratorv1.Orchestrator.CreateBot:output_type -> orchestratorv1.Bot
	1,  // 18: orchestratorv1.Orchestrator.GetBot:output_type -> orchestratorv1.Bot
	4,  // 19: orchestratorv1.Orchestrator.GetAllBots:output_type -> orchestratorv1.GetAllBotsResp
	1,  // 20: orchestratorv1.Orchestrator.StopBot:output_type -> orchestratorv1.Bot
	7,  // 21: orchestratorv1.Orchestrator.StopBots:output_type -> orchestratorv1.StopBotsResp
	1,  // 22: orchestratorv1.Orchestrator.StartBot:output_type -> orchestratorv1.Bot
	10, // 23: orchestratorv1.Orchestrator.StartBots:output_type -> orchestratorv1.StartBotsResp
	1,  // 24: orchestratorv1.Orchestrator.RestartBot:output_type -> orchestratorv1.Bot
	17, // 25: orchestratorv1.Orchestrator.DeleteBot:output_type -> google.protobuf.Empty
	14, // 26: orchestratorv1.Orchestrator.DeleteBots:output_type -> orchestratorv1.DeleteBotsResp
	15, // 27: orchestratorv1.Orchestrator.DeleteAllBots:output_type -> orchestratorv1.DeleteAllBotsResp
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_orchestrator_service_v1_orchestrator_service_proto_init() }
func file_orchestrator_service_v1_orchestrator_service_proto_init() {
	if File_orchestrator_service_v1_orchestrator_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_service_v1_orchestrator_service_proto_rawDesc), len(file_orchestrator_service_v1_orchestrator_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_service_v1_orchestrator_service_proto_goTypes,
		DependencyIndexes: file_orchestrator_service_v1_orchestrator_service_proto_depIdxs,
		EnumInfos:         file_orchestrator_service_v1_orchestrator_service_proto_enumTypes,
		MessageInfos:      file_orchestrator_service_v1_orchestrator_service_proto_msgTypes,
	}.Build()
	File_orchestrator_service_v1_orchestrator_service_proto = out.File
	file_orchestrator_service_v1_orchestrator_service_proto_goTypes = nil
	file_orchestrator_service_v1_orchestrator_service_proto_depIdxs = nil
}
