// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: auth-service/v1/auth-service.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // jwt
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_auth_service_v1_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_v1_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_auth_service_v1_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // uuid
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_auth_service_v1_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_v1_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_auth_service_v1_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type AuthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthReq) Reset() {
	*x = AuthReq{}
	mi := &file_auth_service_v1_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReq) ProtoMessage() {}

func (x *AuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_v1_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReq.ProtoReflect.Descriptor instead.
func (*AuthReq) Descriptor() ([]byte, []int) {
	return file_auth_service_v1_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *AuthReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UpdateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewUsername   string                 `protobuf:"bytes,1,opt,name=new_username,json=newUsername,proto3" json:"new_username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserReq) Reset() {
	*x = UpdateUserReq{}
	mi := &file_auth_service_v1_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserReq) ProtoMessage() {}

func (x *UpdateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_v1_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserReq.ProtoReflect.Descriptor instead.
func (*UpdateUserReq) Descriptor() ([]byte, []int) {
	return file_auth_service_v1_auth_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserReq) GetNewUsername() string {
	if x != nil {
		return x.NewUsername
	}
	return ""
}

var File_auth_service_v1_auth_service_proto protoreflect.FileDescriptor

const file_auth_service_v1_auth_service_proto_rawDesc = "" +
	"\n" +
	"\"auth-service/v1/auth-service.proto\x12\x06authv1\x1a\x1bgoogle/protobuf/empty.proto\"\x1d\n" +
	"\x05Token\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"2\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"A\n" +
	"\aAuthReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"2\n" +
	"\rUpdateUserReq\x12!\n" +
	"\fnew_username\x18\x01 \x01(\tR\vnewUsername2\xfd\x01\n" +
	"\x04Auth\x12*\n" +
	"\bRegister\x12\x0f.authv1.AuthReq\x1a\r.authv1.Token\x12'\n" +
	"\x05Login\x12\x0f.authv1.AuthReq\x1a\r.authv1.Token\x12/\n" +
	"\aGetUser\x12\x16.google.protobuf.Empty\x1a\f.authv1.User\x121\n" +
	"\n" +
	"UpdateUser\x12\x15.authv1.UpdateUserReq\x1a\f.authv1.User\x12<\n" +
	"\n" +
	"DeleteUser\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB;Z9github.com/braunkc/ai-bot-constructor/auth-service;authpbb\x06proto3"

var (
	file_auth_service_v1_auth_service_proto_rawDescOnce sync.Once
	file_auth_service_v1_auth_service_proto_rawDescData []byte
)

func file_auth_service_v1_auth_service_proto_rawDescGZIP() []byte {
	file_auth_service_v1_auth_service_proto_rawDescOnce.Do(func() {
		file_auth_service_v1_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_service_v1_auth_service_proto_rawDesc), len(file_auth_service_v1_auth_service_proto_rawDesc)))
	})
	return file_auth_service_v1_auth_service_proto_rawDescData
}

var file_auth_service_v1_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_auth_service_v1_auth_service_proto_goTypes = []any{
	(*Token)(nil),         // 0: authv1.Token
	(*User)(nil),          // 1: authv1.User
	(*AuthReq)(nil),       // 2: authv1.AuthReq
	(*UpdateUserReq)(nil), // 3: authv1.UpdateUserReq
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_auth_service_v1_auth_service_proto_depIdxs = []int32{
	2, // 0: authv1.Auth.Register:input_type -> authv1.AuthReq
	2, // 1: authv1.Auth.Login:input_type -> authv1.AuthReq
	4, // 2: authv1.Auth.GetUser:input_type -> google.protobuf.Empty
	3, // 3: authv1.Auth.UpdateUser:input_type -> authv1.UpdateUserReq
	4, // 4: authv1.Auth.DeleteUser:input_type -> google.protobuf.Empty
	0, // 5: authv1.Auth.Register:output_type -> authv1.Token
	0, // 6: authv1.Auth.Login:output_type -> authv1.Token
	1, // 7: authv1.Auth.GetUser:output_type -> authv1.User
	1, // 8: authv1.Auth.UpdateUser:output_type -> authv1.User
	4, // 9: authv1.Auth.DeleteUser:output_type -> google.protobuf.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_service_v1_auth_service_proto_init() }
func file_auth_service_v1_auth_service_proto_init() {
	if File_auth_service_v1_auth_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_service_v1_auth_service_proto_rawDesc), len(file_auth_service_v1_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_service_v1_auth_service_proto_goTypes,
		DependencyIndexes: file_auth_service_v1_auth_service_proto_depIdxs,
		MessageInfos:      file_auth_service_v1_auth_service_proto_msgTypes,
	}.Build()
	File_auth_service_v1_auth_service_proto = out.File
	file_auth_service_v1_auth_service_proto_goTypes = nil
	file_auth_service_v1_auth_service_proto_depIdxs = nil
}
