env: develop
grpc:
  host: ${GRPC_HOST}
  port: ${GRPC_PORT}
  orchestrator-service:
    host: ${GRPC_ORCHESTRATOR_HOST}
    port: ${GRPC_ORCHESTRATOR_PORT}
db:
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
logger:
  service: auth-service
  output-type: console
  level: debug